
server:
  port: 8100

spring:
  application:
    name: aichat

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4o-mini

    anthropic:
      api-key: ${ANTHROPIC_API_KEY}

    ollama:
      base-url: http://localhost:11434
  profiles:
    active: dev

# âœ… Gemini must NOT be under spring.ai
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/openai
    completions:
      path: /chat/completions
  model:
    name: gemini-2.5-flash


